Repository firebase/firebase-admin-java, pull requests merged in 2021-06, with the labels that each got.

#569 Revert "chore(deps): bump maven-javadoc-plugin from 3.2.0 to 3.3.0"
  pom.xml
Labels: release:stage

#573 fix: Using Java 8 in release and nightly builds
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  src/main/java/com/google/firebase/FirebaseApp.java
  src/main/java/com/google/firebase/FirebaseOptions.java
  src/main/java/com/google/firebase/auth/internal/Utils.java
  src/main/java/com/google/firebase/database/util/EmulatorHelper.java
  src/main/java/com/google/firebase/internal/ApplicationDefaultCredentialsProvider.java
  src/main/java/com/google/firebase/internal/FirebaseProcessEnvironment.java
  src/test/java/com/google/firebase/FirebaseAppTest.java
  src/test/java/com/google/firebase/auth/EmulatorFirebaseTokenVerifierImplTest.java
  src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
  src/test/java/com/google/firebase/auth/FirebaseTokenUtilsTest.java
  src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
  src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java
  src/test/java/com/google/firebase/database/FirebaseDatabaseTest.java
  src/test/java/com/google/firebase/testing/IntegrationTestUtils.java
  src/test/java/com/google/firebase/testing/TestUtils.java
Labels: release:stage

#576 Drop 500 from the retryable errorcode list
  src/main/java/com/google/firebase/internal/ApiClientUtils.java
  src/test/java/com/google/firebase/internal/ApiClientUtilsTest.java
Labels: release-note

#579 [chore] Release 8.0.0
  pom.xml
Labels: release:publish, release:tweet
