Repository firebase/firebase-admin-java, pull requests merged in 2021-04, with the labels that each got.

#524 chore: Add nightly build workflow
  .github/workflows/nightly.yml
  src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIT.java
Labels: release:stage

#340 feat(auth): Add API to look up users by federated ID.
  src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
  src/main/java/com/google/firebase/auth/FirebaseUserManager.java
  src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
  src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
  src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java
  src/test/resources/getUser.json
  src/test/resources/listUsers.json
Labels: release-note

#345 feat(auth): Link federatedid
  src/main/java/com/google/firebase/auth/UserRecord.java
  src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
  src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
Labels: release-note

#528 Remove the failing integration tests
  src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementIT.java
  src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIT.java
Labels: release:stage

#530 [chore] Release 7.2.0
  pom.xml
Labels: release:publish, release:tweet
