Repository firebase/firebase-admin-java, pull requests merged in 2025-01, with the labels that each got.

#1056 chore: Fix non-existing bucket test
  src/test/java/com/google/firebase/cloud/StorageClientIT.java
Labels: release:stage

#1057 [chore] Release 9.4.3
  pom.xml
Labels: release:stage, release:publish

#1059 fix: `ApiClientUtils.getDefaultTransport()` should return a cached instance to an `ApacheHttp2Transport`
  src/main/java/com/google/firebase/internal/ApiClientUtils.java
  src/test/java/com/google/firebase/internal/ApacheHttp2TransportIT.java
  src/test/java/com/google/firebase/internal/ApiClientUtilsTest.java
Labels: release-note, release:stage

#1065 fix: use .equals() instead of == for strings
  src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
  src/main/java/com/google/firebase/auth/UserRecord.java
Labels: release-note
